### ISSUE TITLE
Turing Complete?

### ISSUE THREAD

**Issue by Chobbes** [TheLastBanana/Churro#1]
While I may concede that Churro is Churring complete, it is in fact quite possibly not Turing complete. In my sleep deprived state it appears that Churro may in fact be equivalent to a PDA with an additional 9999 slots of memory, but it is unclear that this results in a Turing complete system.

CALVIN IS IRKED BY MUTABLE STATE WHICH IS ALSO INSUFFICIENT.

**Comment by TheLastBanana** [comment]
The current specification does not claim to be Turing complete. However, I may change the specification to allow for any number of memory slots, therefore allowing the implementation to decide whether the language is Turing complete.

**Comment by TheLastBanana** [comment]
The specification has been changed as mentioned above. The interpreter has also been updated to use a dictionary, providing a (theoretically) infinite array size. The internal number representation has been switched from 32-bit Ints to Integers, so array indices can be arbitrarily large. As such, Churro should now be Turing complete, at least as much so as any other programming language.
