### ISSUE TITLE
Churro not yet listed at esolangs.org

### ISSUE THREAD

**Issue by kdbanman** [TheLastBanana/Churro#3]
Comparing Churro with a few other languages on the [esoteric language list](https://esolangs.org/wiki/Language_list) should convince anyone that it's a worthy candidate.  And not just for the [joke language list](https://esolangs.org/wiki/Joke_language_list).

Churro's [website](https://webdocs.cs.ualberta.ca/~colp/churro/) content and README content together comprise more complete documentation than most other languages on esolangs.org.  Perhaps they could be mirored there as an article.

**Comment by TheLastBanana** [comment]
Good point. I've mirrored the relevant parts of the README on the wiki and spruced it up with a little formatting:

https://esolangs.org/wiki/Churro
